// API mock para restaurantes mais recentes
export default function handler(req, res) {
    const mockLatestRestaurants = {
        total_size: 5,
        limit: 10,
        offset: 0,
        data: [
            {
                id: 4,
                name: 'Banca da Ana',
                phone: '(11) 99999-0004',
                email: 'ana@bancasdobairro.com',
                logo: '/static/food.png',
                logo_full_url: '/static/food.png',
                cover_photo_full_url: '/static/image.png',
                latitude: '-23.574321',
                longitude: '-46.648765',
                address: 'Rua dos Três Irmãos, 321 - Vila Progredior, São Paulo - SP',
                footer_text: 'Produtos orgânicos e sustentáveis',
                minimum_order: 20.00,
                comission: 0,
                schedule_order: true,
                status: 1,
                vendor_id: 4,
                delivery_time: '35-50',
                veg: 1,
                non_veg: 0,
                order_count: 12,
                total_order: 12,
                rating_count: 5,
                positive_rating: 5,
                avg_rating: 5.0,
                tax: 0,
                delivery: 1,
                take_away: 1,
                food_section: 1,
                tax_status: 1,
                delivery_charge: 7.00,
                available_time_starts: '09:00:00',
                available_time_ends: '19:00:00',
                off_day: 'monday',
                self_delivery_system: 0,
                pos_system: 0,
                minimum_shipping_charge: 7.00,
                maximum_shipping_charge: 20.00,
                per_km_shipping_charge: 3.00,
                restaurant_model: 'none',
                maximum_delivery_time: '50',
                cutlery: 0,
                slug: 'banca-da-ana',
                order_subscription_active: 0,
                instant_order: 1,
                announcement: 1,
                announcement_message: 'Inauguração! 15% de desconto na primeira compra',
                qr_code: null,
                additional_data: null,
                additional_documents: null,
                translations: [],
                storage: [],
                schedules: [],
                discount: {
                    id: 1,
                    start_date: '2024-01-01',
                    end_date: '2024-01-31',
                    start_time: '00:00:00',
                    end_time: '23:59:59',
                    min_purchase: 15.00,
                    max_discount: 10.00,
                    discount: 15.00,
                    discount_type: 'percent'
                },
                cuisine: [],
                characteristics: [],
                category_ids: [],
                open: 1,
                active: true
            },
            {
                id: 5,
                name: 'Banca do Carlos',
                phone: '(11) 99999-0005',
                email: 'carlos@bancasdobairro.com',
                logo: '/static/food.png',
                logo_full_url: '/static/food.png',
                cover_photo_full_url: '/static/image.png',
                latitude: '-23.545678',
                longitude: '-46.612345',
                address: 'Av. Rebouças, 987 - Pinheiros, São Paulo - SP',
                footer_text: 'Lanches rápidos e saborosos',
                minimum_order: 10.00,
                comission: 0,
                schedule_order: true,
                status: 1,
                vendor_id: 5,
                delivery_time: '15-30',
                veg: 0,
                non_veg: 1,
                order_count: 8,
                total_order: 8,
                rating_count: 3,
                positive_rating: 3,
                avg_rating: 4.7,
                tax: 0,
                delivery: 1,
                take_away: 1,
                food_section: 1,
                tax_status: 1,
                delivery_charge: 3.50,
                available_time_starts: '06:00:00',
                available_time_ends: '23:00:00',
                off_day: '',
                self_delivery_system: 0,
                pos_system: 0,
                minimum_shipping_charge: 3.50,
                maximum_shipping_charge: 10.00,
                per_km_shipping_charge: 1.50,
                restaurant_model: 'none',
                maximum_delivery_time: '30',
                cutlery: 0,
                slug: 'banca-do-carlos',
                order_subscription_active: 0,
                instant_order: 1,
                announcement: 0,
                announcement_message: null,
                qr_code: null,
                additional_data: null,
                additional_documents: null,
                translations: [],
                storage: [],
                schedules: [],
                discount: null,
                cuisine: [],
                characteristics: [],
                category_ids: [],
                open: 1,
                active: true
            },
            {
                id: 3,
                name: 'Banca do Pedro',
                phone: '(11) 99999-0003',
                email: 'pedro@bancasdobairro.com',
                logo: '/static/food.png',
                logo_full_url: '/static/food.png',
                cover_photo_full_url: '/static/image.png',
                latitude: '-23.533773',
                longitude: '-46.625290',
                address: 'Rua Augusta, 789 - Consolação, São Paulo - SP',
                footer_text: 'Açaí premium e vitaminas funcionais',
                minimum_order: 18.00,
                comission: 0,
                schedule_order: true,
                status: 1,
                vendor_id: 3,
                delivery_time: '20-35',
                veg: 1,
                non_veg: 0,
                order_count: 203,
                total_order: 203,
                rating_count: 67,
                positive_rating: 63,
                avg_rating: 4.7,
                tax: 0,
                delivery: 1,
                take_away: 1,
                food_section: 1,
                tax_status: 1,
                delivery_charge: 6.00,
                available_time_starts: '08:00:00',
                available_time_ends: '21:00:00',
                off_day: '',
                self_delivery_system: 0,
                pos_system: 0,
                minimum_shipping_charge: 6.00,
                maximum_shipping_charge: 18.00,
                per_km_shipping_charge: 2.50,
                restaurant_model: 'none',
                maximum_delivery_time: '35',
                cutlery: 0,
                slug: 'banca-do-pedro',
                order_subscription_active: 0,
                instant_order: 1,
                announcement: 0,
                announcement_message: null,
                qr_code: null,
                additional_data: null,
                additional_documents: null,
                translations: [],
                storage: [],
                schedules: [],
                discount: null,
                cuisine: [],
                characteristics: [],
                category_ids: [],
                open: 1,
                active: true
            }
        ]
    };

    // Simular delay de rede
    setTimeout(() => {
        res.status(200).json(mockLatestRestaurants);
    }, 100);
}