// API mock para restaurantes populares
export default function handler(req, res) {
    const mockRestaurants = {
        total_size: 8,
        limit: 10,
        offset: 0,
        restaurants: [
            {
                id: 1,
                name: 'Banca do João',
                phone: '(11) 99999-0001',
                email: 'joao@bancasdobairro.com',
                logo: '/static/food.png',
                latitude: '-23.550520',
                longitude: '-46.633308',
                address: 'Rua das Flores, 123 - Vila Madalena, São Paulo - SP',
                footer_text: 'Produtos frescos e naturais',
                minimum_order: 15.00,
                comission: 0,
                schedule_order: true,
                status: 1,
                vendor_id: 1,
                delivery_time: '30-45',
                veg: 0,
                non_veg: 1,
                order_count: 150,
                total_order: 150,
                rating_count: 45,
                positive_rating: 42,
                avg_rating: 4.5,
                tax: 0,
                delivery: 1,
                take_away: 1,
                food_section: 1,
                tax_status: 1,
                delivery_charge: 5.00,
                available_time_starts: '06:00:00',
                available_time_ends: '22:00:00',
                off_day: '',
                self_delivery_system: 0,
                pos_system: 0,
                minimum_shipping_charge: 5.00,
                maximum_shipping_charge: 15.00,
                per_km_shipping_charge: 2.00,
                restaurant_model: 'none',
                maximum_delivery_time: '45',
                cutlery: 0,
                slug: 'banca-do-joao',
                order_subscription_active: 0,
                instant_order: 1,
                announcement: 0,
                announcement_message: null,
                qr_code: null,
                additional_data: null,
                additional_documents: null,
                translations: [],
                storage: [],
                schedules: [],
                discount: null,
                cuisine: [],
                characteristics: [],
                category_ids: [],
                open: 1,
                active: true
            },
            {
                id: 2,
                name: 'Banca da Maria',
                phone: '(11) 99999-0002',
                email: 'maria@bancasdobairro.com',
                logo: '/static/food.png',
                latitude: '-23.561414',
                longitude: '-46.656166',
                address: 'Av. Paulista, 456 - Bela Vista, São Paulo - SP',
                footer_text: 'Sanduíches artesanais e sucos naturais',
                minimum_order: 12.00,
                comission: 0,
                schedule_order: true,
                status: 1,
                vendor_id: 2,
                delivery_time: '25-40',
                veg: 1,
                non_veg: 1,
                order_count: 89,
                total_order: 89,
                rating_count: 28,
                positive_rating: 26,
                avg_rating: 4.2,
                tax: 0,
                delivery: 1,
                take_away: 1,
                food_section: 1,
                tax_status: 1,
                delivery_charge: 4.50,
                available_time_starts: '07:00:00',
                available_time_ends: '20:00:00',
                off_day: 'sunday',
                self_delivery_system: 0,
                pos_system: 0,
                minimum_shipping_charge: 4.50,
                maximum_shipping_charge: 12.00,
                per_km_shipping_charge: 1.80,
                restaurant_model: 'none',
                maximum_delivery_time: '40',
                cutlery: 0,
                slug: 'banca-da-maria',
                order_subscription_active: 0,
                instant_order: 1,
                announcement: 0,
                announcement_message: null,
                qr_code: null,
                additional_data: null,
                additional_documents: null,
                translations: [],
                storage: [],
                schedules: [],
                discount: null,
                cuisine: [],
                characteristics: [],
                category_ids: [],
                open: 1,
                active: true
            },
            {
                id: 3,
                name: 'Banca do Pedro',
                phone: '(11) 99999-0003',
                email: 'pedro@bancasdobairro.com',
                logo: '/static/food.png',
                latitude: '-23.533773',
                longitude: '-46.625290',
                address: 'Rua Augusta, 789 - Consolação, São Paulo - SP',
                footer_text: 'Açaí premium e vitaminas funcionais',
                minimum_order: 18.00,
                comission: 0,
                schedule_order: true,
                status: 1,
                vendor_id: 3,
                delivery_time: '20-35',
                veg: 1,
                non_veg: 0,
                order_count: 203,
                total_order: 203,
                rating_count: 67,
                positive_rating: 63,
                avg_rating: 4.7,
                tax: 0,
                delivery: 1,
                take_away: 1,
                food_section: 1,
                tax_status: 1,
                delivery_charge: 6.00,
                available_time_starts: '08:00:00',
                available_time_ends: '21:00:00',
                off_day: '',
                self_delivery_system: 0,
                pos_system: 0,
                minimum_shipping_charge: 6.00,
                maximum_shipping_charge: 18.00,
                per_km_shipping_charge: 2.50,
                restaurant_model: 'none',
                maximum_delivery_time: '35',
                cutlery: 0,
                slug: 'banca-do-pedro',
                order_subscription_active: 0,
                instant_order: 1,
                announcement: 0,
                announcement_message: null,
                qr_code: null,
                additional_data: null,
                additional_documents: null,
                translations: [],
                storage: [],
                schedules: [],
                discount: null,
                cuisine: [],
                characteristics: [],
                category_ids: [],
                open: 1,
                active: true
            }
        ]
    };

    // Simular delay de rede
    setTimeout(() => {
        res.status(200).json(mockRestaurants);
    }, 100);
}